name: "Sync upstream"
description: "Checks upstream, merges if possible, creates PR if conflicts."

inputs:
  upstream-url:
    description: "GitHub repository URL of the upstream (e.g., https://github.com/owner/repo.git)"
    required: true

  upstream-branch:
    description: "Branch name of the upstream (e.g., main)"
    required: false
    default: "main"

  target-branch:
    description: "Branch name of the target repository to sync (e.g., main)"
    required: false
    default: "main"

  user-email:
    description: "Git user.email"
    required: false
    default: "action@github.com"

  user-name:
    description: "Git user.name"
    required: false
    default: "GitHub Action"

  pr-title:
    description: "Pull Request title when creating a PR"
    required: false
    default: "Merge upstream changes"

  pr-body:
    description: "Pull Request body when creating a PR"
    required: false
    default: "This PR merges changes from upstream."

  pr-branch-prefix:
    description: "Branch name prefix when creating a PR"
    required: false
    default: "sync-upstream"

  always-use-pr:
    description: "Always create a pull request instead of direct push (useful for branch protection)"
    required: false
    default: "false"

  github-token:
    description: "GitHub token"
    required: true

runs:
  using: node20
  main: dist/index.js
