# ================================================================
# Settings
# ================================================================
[settings]
auto_install = false
minimum_release_age = "3d"


# ================================================================
# Tools
# ================================================================
[tools]
# Markdown
markdownlint-cli2 = "latest"

# GitHub Actions
actionlint = "latest"
shellcheck = "0.11.0"   # for actionlint
zizmor = "1.26.1"

# JavaScript
pnpm = "latest"

# Git
lefthook = "2.1.10"
gitleaks = "8"


# ================================================================
# Tasks
# See: https://mise.jdx.dev/tasks/toml-tasks.html
# ================================================================

[tasks.setup]
description = "Setup tools"
run = ["mise trust -yq", "mise install", "lefthook install"]
alias = "s"

[tasks.fix]
description = "Fix all issues"
depends = ["md-fix", "gh-fix", "js-fix"]
alias = "f"

[tasks.check]
description = "Check for all issues"
depends = ["md-check", "gh-check", "gitleaks-check", "js-check"]
alias = "c"

[tasks.fix-and-check]
description = "Fix all issues and check for issues"
run = [{ task = "fix" }, { task = "check" }]
alias = "fc"

# Markdown
[tasks.md-fix]
description = "Fix Markdown issues"
run = "markdownlint-cli2 . --fix"
alias = "mf"

[tasks.md-check]
description = "Check for Markdown issues"
run = "markdownlint-cli2 ."
alias = "mc"

# GitHub Actions
[tasks.gh-fix]
description = "Fix GitHub Actions workflows"
run = "zizmor --fix=all ."
alias = "ghf"

[tasks.gh-check]
description = "Check GitHub Actions workflows"
run = [
  "actionlint .github/workflows/*.yml",
  "zizmor . --persona=pedantic --min-severity=medium",
]
alias = "ghc"

# Secrets
[tasks.gitleaks-check]
description = "Check for leaked secrets"
run = "gitleaks git --redact --no-banner"
alias = "glc"

[tasks.gitleaks-protect]
description = "Check staged files for leaked secrets"
run = "gitleaks git --pre-commit --redact --no-banner"
alias = "glp"

# JavaScript
[tasks.js-install]
description = "Install JavaScript dependencies"
run = "pnpm install"

[tasks.js-build]
description = "Build JavaScript project"
run = "pnpm build"
alias = "b"

[tasks.js-fix-and-check]
description = "Fix and check JavaScript"
depends = ["js-fix"]
run = "mise run js-check"
alias = "jfc"

[tasks.js-fix]
description = "Fix JavaScript issues"
depends = ["js-fmt", "js-lint-fix"]

[tasks.js-check]
description = "Check JavaScript"
depends = ["js-fmt-check", "js-lint", "js-test"]

[tasks.js-fmt]
description = "Format JavaScript"
run = "pnpm format"

[tasks.js-fmt-check]
description = "Check JavaScript formatting"
run = "pnpm format:check"

[tasks.js-lint]
description = "Lint JavaScript"
run = "pnpm lint"

[tasks.js-lint-fix]
description = "Fix JavaScript linting issues"
run = "pnpm lint:fix"

[tasks.js-test]
description = "Run JavaScript tests"
run = "pnpm test"

[tasks.js-test-watch]
description = "Run JavaScript tests in watch mode"
run = "pnpm test:watch"

# mise lock
[tasks.lock-fix]
description = "Update mise.lock"
run = "mise lock"
alias = "lf"

[tasks.lock-check]
description = "Check mise.lock is up to date"
run = ["mise lock", "git diff --exit-code -- mise.lock"]
alias = "lc"
