[tools]
# YAML
uv = "latest"       # for install yamllint
yamllint = "latest"

# Markdown
markdownlint-cli2 = "latest"

# JSON
biome = "latest"

# GitHub Actions
actionlint = "latest"
shellcheck = "0.10"   # for actionlint

# JavaScript
pnpm = "latest"
